services:
  typesense:
    image: typesense/typesense:26.0
    restart: on-failure
    ports:
      - '8108:8108'
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
    environment:
      - TYPESENSE_SERVER_CORS_ALLOW_ORIGINS=*
    extra_hosts:
      - 'host.docker.internal:host-gateway'
